name: .NET

on:
  workflow_dispatch
#  push:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019
    concurrency: build

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  publish:
    needs: build 
    runs-on: windows-2019
    concurrency: publish
    
    steps:
    - name: Publish Release
      run: dotnet publish ../StuartAitken.Blazor.sln -c Release -o ./publish

  deploy:
    needs: [build, publish]
    runs-on: windows-2019
    concurrency: deploy
    
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: FTP to HostWinds Server
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.HOSTWINDS_SERVER }}
          user: ${{ secrets.HOSTWINDS_USER }}
          password: ${{ secrets.HOSTWINDS_PASS }}
          local_dir: "./publish"
          remote_dir: "./StuartAitken.Blazor"
          delete: "false"
