name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build
    defaults:
      run:
        working-directory: ${{ github.workspace }}
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish Release
      run: dotnet publish -c Release -o ./publish -r win10-x64 --self-contained false
      
    - name: FTP to HostWinds Server
      uses:  sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.HOSTWINDS_SERVER }}
        user: ${{ secrets.HOSTWINDS_USER }}
        password: ${{ secrets.HOSTWINDS_PASS }}
        localDir: "./publish"
        remoteDir: "./StuartAitken.Blazor"
        options: "--delete --asci -x /wwwroot/images/projectImages/ -x /Database/ -x web.config"
